config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/new'
  resources :products
  get 'top/main'
  root 'top#main'
  resources :cart_items, only: [:new, :create, :destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
    def create
        tweet = Tweet.find(params[:tweet_id])
        user = User.find_by(uid: session[:login_uid])
        user.like_tweets << tweet
        redirect_to root_path
    end
    def destroy
        tweet = Tweet.find(params[:id])
        user = User.find_by(uid: session[:login_uid])
        tweet.likes.find_by(user_id: user.id).destroy
        redirect_to root_path
    end
    
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet
    belongs_to :user
    belongs_to :tweet
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :tweets
    has_many :likes, dependent: :destroy
    has_many :likes_users, source: :user, through: :likes
end

app/models/user.rb
class User < ApplicationRecord
    has_one :profile
    has_many :tweets, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :like_tweets, source: :tweet, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
    private
    
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def new
    @cart_id = current_cart
    @product_id = params[:product_id]
    @cart_item = CartItem.new
  end
  
  def create
    @cart_id = params[:cart_item][:cart_id]
    @product_id = params[:cart_item][:product_id]
    @qty = params[:cart_item][:qty]
    c = CartItem.new(cart_id: @cart_id, product_id: @product_id, qty: @qty)
    if c.save
      redirect_to root_path
    else
      render "new"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    user = User.find_by(uid: current_user)
    user.like_tweets << tweet
    redirect_to root_path
  end
  
  def like(user)
    likes.create(user_id: user.id)
  end
  
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  
  def liked?(user)
    like_users.inckude?(user)
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    user = User.find_by(uid: current_user)
    tweet.likes.find_by(user_id: user.id).destroy
    redirect_to root_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    @tweets = Tweet.all
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
        @tweet = Tweet.new
    end
    
    def create
        @tweet = Tweet.new(message: params[:tweet][:message])
        @tweet.save
        redirect_to root_path
    end
    
    def destroy
        Tweet.find(params[:id]).destroy
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(uid: params[:user][:uid], pass: params[:user][:pass], age: params[:user][:age])
        if @user.save
            redirect_to users.path
        else
            render 'new'
        end
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/new.html.erb
<%= form_for @cart_item, url: {action: :create} do |f| %>
    <%= Product.find(@product_id).name %>
    <%= f.label :qty, '数量' %>
    <%= f.text_field :qty %>
    <%= f.hidden_field :product_id, @product_id %>
    <%= f.hidden_field :cart_id, value: @cart_id %>
    <%= f.submit 'カートに登録する' %>
<% end %>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/products/index.html.erb
<% @products.each do |e| %>

<p>
    <%= e.name %>
    <%= e.price %>
    <%= link_to '削除', products_path(e), data: {"turbo-method": :delete} %>
    <%= link_to 'カートに入れる', cart_items_new_path(product_id: e.id) %>
</p>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

app/views/top/main.html.erb
<%= stylesheet_link_tag "application.css", :meddia=>"all" %>

<% if flash[:notice] %>
    <% flash[:notice] %>
<% end %>

<% @tweets.each do |e| %>
    <p>
        <div id=tweet>
            <%= e.message %>
            <%=link_to '削除', "/tweets/#{e.id}", data: { turbo_method: :delete } %>
            <%=link_to '表示', "/tweets/#{e.id}" %>
            <%=link_to '編集', "/tweets/#{e.id}/edit" %>
        </div>
    </p>
<% end %>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag "application.css", :meddia=>"all" %>

<% if flash[:notice] %>
    <% flash[:notice] %>
<% end %>

<% @tweets.each do |e| %>
    <p>
        <div id=tweet>
            <%= e.message %>
            <%=link_to '削除', "/tweets/#{e.id}", data: { turbo_method: :delete } %>
        </div>
    </p>
<% end %>

<%= form_for @tweet, url: {action: :create} do |f| %>
    <%= f.label :message, 'message' %>
    <%= f.text_field :message %>
    <%= f.submit 'ツイート' %>
<% end %>

<%= link_to 'ユーザー一覧', users_path %>

app/views/tweets/tweets.html.erb
<% @tweets.each do |e| %>
    <%= e.message %>
    <%= link_to 'いいね', likes_path(tweet_id: e.id), method: :post %>
    <%= link_to 'いいね削除', like_path(e), method: :delete %>
<% end %>

app/views/users/index.html.erb
<%= stylesheet_link_tag "application.css", :meddia=>"all" %>

<% if flash[:notice] %>
    <% flash[:notice] %>
<% end %>

<% @tweets.each do |e| %>
    <p>
        <div id=tweet>
            <%= e.message %>
            <%=link_to '削除', "/tweets/#{e.id}", data: { turbo_method: :delete } %>
            <%=link_to '表示', "/tweets/#{e.id}" %>
            <%=link_to '編集', "/tweets/#{e.id}/edit" %>
        </div>
    </p>
<% end %>

app/views/users/new.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to "削除", user_path(user), method: :delete, data: { confirm: "これでいいですか?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "新しいUser", new_user_path %>